name: Generate and Commit Project Structure

on:
  push:

jobs:
  update_project_structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Tree Command
        run: sudo apt-get install -y tree

      - name: Print Working Directory
        run: pwd

      - name: List Files in Directory
        run: ls -la

      - name: Generate Project Structure
        run: |
          echo "Project Structure:" > Project_Structure.txt
          echo "Running tree command:" >> Project_Structure.txt
          tree -I '.git|node_modules|.github|*.md' >> Project_Structure.txt

      - name: Display Project Structure
        run: cat Project_Structure.txt

      - name: Check if Project_Structure.txt Exists
        id: check_file
        run: |
          if [ -f Project_Structure.txt ]; then
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "file_exists=false" >> $GITHUB_ENV
          fi

      - name: Debug Project Structure Changes
        if: env.file_exists == 'true'
        run: |
          git fetch
          echo "Checking differences:"
          git diff origin/main -- Project_Structure.txt
          if git diff --quiet origin/main -- Project_Structure.txt; then
            echo "No changes in Project_Structure.txt"
          else
            echo "Changes detected in Project_Structure.txt"
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add Project_Structure.txt
            git commit -m "Create or Update Project Structure"
            git push
          fi
