name: Generate and Commit Project Structure

on:
  push:

jobs:
  update_project_structure:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Tree Command
      run: sudo apt-get install tree

    - name: Print Working Directory
      run: pwd

    - name: Generate Project Structure
      run: |
        echo "Project Structure:" > Project_Structure.txt
        echo "Running tree command:"
        tree -I '.git|node_modules|.github|*.md'
        tree -I '.git|node_modules|.github|*.md' >> Project_Structure.txt

    - name: Display Project Structure
      run: cat Project_Structure.txt

    - name: Check if Project_Structure.txt Exists
      id: check_file
      run: |
        if [ -f Project_Structure.txt ]; then
          echo "file_exists=true" >> $GITHUB_ENV
        fi

    - name: Commit and Push Changes
      if: env.file_exists == 'true'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add Project_Structure.txt
        git diff --staged --exit-code --quiet || exit 0  # This line checks for changes
        git commit -m "Create or Update Project Structure"
        git push

