name: Generate and Commit Project Structure

on:
  push:

jobs:
  update_project_structure:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Tree Command
      run: sudo apt-get install tree

    - name: Print Working Directory
      run: pwd

    - name: Generate Project Structure
      run: |
        echo "Project Structure:" > Project_Structure.txt
        echo "Running tree command:"
        tree -I '.git|node_modules|.github|*.md'
        tree -I '.git|node_modules|.github|*.md' >> Project_Structure.txt

    - name: Display Project Structure
      run: cat Project_Structure.txt

    - name: Check for Changes
      run: |
        git diff --exit-code Project_Structure.txt || echo "changes=true" >> $GITHUB_ENV

    - name: Commit and Push Changes
      if: env.changes == 'true'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add Project_Structure.txt
        git commit -m "Update Project Structure"
        git push
